# ä¸»é¢˜é…ç½®
theme = "weii"
baseURL = "https://example.com"
languageCode = "zh-cn"
# é»˜è®¤åˆ†é¡µæ•°é‡
paginate = 10
enableEmoji = true

# ç«™ç‚¹åœ°å›¾
[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

# é“¾æ¥é…ç½®ä¸hexoçš„æ ¼å¼ç›¸åŒ,æ— ç¼è¿ç§»
[permalinks]
    posts = "/:year/:month/:day/:filename/"

# åˆ†ç±»é…ç½®
[taxonomies]
    category = "categories"
    tag = "tags"

# é…ç½®èœå•
[[menu.main]]
    name = "é¦–é¡µ"
    weight = 10
    identifier = "home"
    url = "/"
    icon = ""
[[menu.main]]
    name = "å½’æ¡£"
    weight = 20
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "åˆ†ç±»"
    weight = 30
    identifier = "categories"
    url = "/categories/"
[[menu.main]]
    name = "æ ‡ç­¾"
    weight = 40
    identifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "å…³äº"
    weight = 50
    identifier = "about"
    url = "/about/"

[params]
    # ç½‘ç«™ä½œè€…
    author = "wilson"
    # ç½‘ç«™æ ‡é¢˜
    title = "wilson's blog"
    # ç½‘ç«™äºŒçº§æ ‡é¢˜
    subTitle = "Life is short, you need Python"
    # ç½‘ç«™æè¿°
    description = "Ù©(à¹‘â›á´—â›à¹‘)Û¶"

# weiiä¸»é¢˜æ–‡ä»¶é…ç½®ç›¸å…³
[params.weii]
    # ç½‘ç«™logo
    logo = "images/logo.png"
    # ç½‘ç«™åˆ›å»ºå¹´ä»½
    since = "2014"
    # å¤´åƒ
    avatar = "images/avatar.png"
    # åœè’œå­è®¿é—®è®¡æ•°
    busuanzi = true
    # ç½‘ç«™å…³é”®å­— site's keywords
    keywords = ["weii","wevsmy","wilson","Python","Golang","PyQt5","hugo","gohugo"]
    # æ ‡ç­¾é¢œè‰²
    tags_color = ["#13af72","#0f233e","#4a0035","#ae985e","#47aaff"]
    # å…¨å±€ä¸»é¢˜é¢œè‰²
    theme_color = "#333333"
    # https://creativecommons.org/licenses/
    # by | by-sa | by-nd | by-nc | by-nc-sa | by-nc-nd
    # è®¸å¯è¯
    creative_commons = "by-nc-sa"
    # googleåˆ†æ
    google_analytics = ""
    # Googleé¡µé¢éªŒè¯
    google_verification = "LY-yWUgw7WEmNuBW7lLOj8jSiKZEVgOCmsisfGWtZCg"
    # å¿…åº”é¡µé¢éªŒè¯
    bing_content_verification = "1A54BC0D6A4D102B72F2A0E9870611FA"

# Transform your image to those favicons in https://realfavicongenerator.net/.
# ç½‘ç«™icon
[params.weii.favicons]
    apple_touch_icon = "favicons/apple-touch-icon.png"
    android_chrome_large = "favicons/android-chrome-96x96.png"
    medium = "favicons/favicon-32x32.png"
    small = "favicons/favicon-16x16.png"
    safari_pinned_tab = "favicons/safari-pinned-tab.svg"
    android_manifest = "favicons/site.webmanifest"
    ms_browserconfig = "favicons/browserconfig.xml"
    fallback = "favicons/favicon.ico"

# ç¤¾äº¤è¿æ¥
# å›¾æ ‡ https://www.iconfont.cn
# icon class
[[params.weii.social]]
    name = "GitHub"
    url = "https://github.com/wevsmy"
    tip = "O__O "
    icon_class = "iconfont icongithub-fill"
[[params.weii.social]]
    name = "Weibo"
    url = "https://weibo.com/wevsmy"
    tip = "O__O "
    icon_class = "iconfont iconweibo"
[[params.weii.social]]
    name = "E-Mail"
    url = "mailto:wevsmy@gmail.com"
    tip = "O__O "
    icon_class = "iconfont iconmail"

# å‹æƒ…é“¾æ¥
[[params.weii.blogroll]]
    name = "wilson's blog"
    url = "https://blog.weii.ink"
    tip = "â•®(â•¯â–½â•°)â•­"
    icon_class = "iconfont iconcode"
[[params.weii.blogroll]]
    name = "GitHub"
    url = "https://github.com/wevsmy"
    tip = "O__O "
    icon_class = "iconfont icongithub-fill"
[[params.weii.blogroll]]
    name = "å‹é“¾æ‹›ç§ŸğŸ¤ª"
    url = "https://github.com/wevsmy"
    tip = "O__O "
    icon_class = "iconfont iconheart"

# è¯„è®º
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.weii.comment]
    enable = true
[params.weii.comment.disqus]
    enable = false
    disqusShortname = "wevsmy"
[params.weii.comment.commentjs]
    enable = true
    type = "github"
    user = "wevsmy"
    repo = "wevsmy.github.io"
    client_id = "ded8625909c20b7ae2f7"
    client_secret = "c9ba27c5047486b4e2e0f8c3001aae33bc15374a"
[params.weii.comment.valine]
    enable = true
    appId = ""
    appKey = ""
    placeholder = " "
    visitor = true

# CDN
[params.weii.lib_cdn]
    enable = true
    weii_iconfont_css = "https://at.alicdn.com/t/font_1354893_48p2lem7d2u.css"
    bootstrap_min_css = "https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
    jquery_min_js = "https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
    bootstrap_min_js = "https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
    busuanzi_pure_mini_js = "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
    canvas_nest_js = ""

# Then set different fonts to different parts here.
# è‡ªå®šä¹‰å›¾æ ‡ https://www.iconfont.cn
# icon class
[params.weii.custom]
    enable = false
    iconfont_css = "https://at.alicdn.com/t/font_1354893_senbplqdck.css"

# æ‰“èµ
[params.weii.reward]
    enable = true
    comment = "ğŸğŸè¿˜æ˜¯è¦æ”¾çš„ï¼Œä¸‡ä¸€çœŸæœ‰äººæ”¯æŒå˜ï¼ğŸ¤£ğŸ¤£"
    wechatpay_qrcode = "images/WeChatPay.png"
    alipay_qrcode = "images/AliPay.png"

# ç‰¹æ•ˆ
[params.weii.effect]
    # å¤´åƒè½¬åŠ¨æ•ˆæœ
    animate = false
    # canvas-nest.js
    canvas_nest = true
    # é¼ æ ‡ç‚¹å‡»å‡ºç°å°å¿ƒå¿ƒlove
    mouse_click_love = true
    # é¼ æ ‡ç‚¹å‡»å‡ºç°â€œæ­£èƒ½é‡â€ magic
    mouse_click_magic = false
